### ISSUE TITLE
Roadmap for package release

### ISSUE THREAD

**Issue by IhsanKhaliq** [IhsanKhaliq/ascotraceR#86]
- [x] All tests need to pass on `dev` branch of the `ascotraceR` package. When all tests passed, it can be merged into `master` branch before submitting resource announcement paper for reviewers to review. 

- [x] Figures based on model validation are on the `ms` branch of the `valascotraceR` repository created for model validation. This doesn't require any change now (unless we want to modify figures), but just needs to be merged with `master` branch when submitting paper to avoid confusions and for review purposes

- [x] Add README files

- [x] Submitting the package to CRAN (only if there is a requirement for CRAN submission in the resource announcement/package paper. Doesn't require for the model paper)

**Comment by IhsanKhaliq** [comment]
Road map is clear. Only CRAN submission is pending

**Comment by adamhsparks** [comment]
There’s no reason to close this early. There’s still one item left in the roadmap, submission to CRAN. Once that’s done we will close this issue.
